// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqgfkzmnrhevgxknlpcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZ2Zrem1ucmhldmd4a25scGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMTIwMDcsImV4cCI6MjA1MTc4ODAwN30.qOU7AG7yeIa_bmCxgBAH2i5L9Q_F0Wyu3YBULvdgJmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);